name: Test

on:
  push:
    branches: 
    - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python3
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - name: Test
      run: python3 check_digit.py
